worker_processes  1;

events {
	worker_connections 1024;
}


http {
       include mime.types;
       sendfile on;
       client_max_body_size 20m;

       server {
	listen 8080;

        location = /_validate {
            internal;
	    proxy_method GET;
            proxy_pass http://security:3000/v1/token/validation;
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
            proxy_set_header Authorization $http_authorization;
        }

	location = /v1/register {
		proxy_pass http://security:3000/v1/user;
		proxy_set_header Host $host;
		proxy_set_header Content-Type $http_content_type;
	}
	
	location = /v1/token {
		proxy_pass http://security:3000/v1/token;
		proxy_set_header Host $host;
		proxy_set_header Content-Type $http_content_type;
        }

	location = /token {
		proxy_pass http://security:3000/v1/token;
		proxy_set_header Host $host;
		proxy_set_header Content-Type $http_content_type;
	}

	location = /v1/user {
		auth_request /_validate;
		proxy_pass http://security:3000/v1/user;
		proxy_set_header Host $host;
		proxy_set_header Content-Type $http_content_type;
	}

	location /v1/user/ {
		auth_request /_validate;
		rewrite ^/v1/user/(.+)$ /data/$1 break;
		proxy_pass http://storage:9000;
		proxy_set_header Host storage:9000;
		proxy_set_header Authorization "";
	}

	location = /v1/upload {
		auth_request /_validate;
		proxy_pass http://uploader:3000/v1/upload;
		proxy_set_header Host $host;
	}

	location = /upload {
		auth_request /_validate;
		proxy_pass http://uploader:3000/v1/upload;
		proxy_set_header Host $host;
                proxy_set_header Content-Type $http_content_type;
	}

        location /data/ {
                auth_request /_validate;
                proxy_pass http://storage:9000;
                proxy_set_header Host storage:9000;
                proxy_set_header Authorization "";
        }

        location /images/ {
                auth_request /_validate;
                rewrite ^/images/(.+)$ /data/$1 break;
                proxy_pass http://storage:9000;
                proxy_set_header Host storage:9000;
                proxy_set_header Authorization "";
        }   
    }
}    
