input {
  kafka {
    bootstrap_servers => "kafka:9092"
    topics => ["logs-microservices"]
    group_id => "logstash-elk"
    codec => json
    consumer_threads => 3
    auto_offset_reset => "earliest"
  }
}

filter {
  if [message] =~ /^\{/ {
    json { source => "message" }
  }
  mutate {
    add_field => { "[@metadata][date]" => "%{+YYYY.MM.dd}" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "logs-%{[@metadata][date]}"
  }
}
